# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Todoey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todoey
pod "RealmSwift"
#pod "SwipeCellKit", :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'develop'
pod "SwipeCellKit", '2.5.4'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
